# Bijectors are used to transform tensor objects

In [1]:
import tensorflow as tf
import tensorflow_probability as tfp
from keras.models import Sequential, Model
from tensorflow import keras
from keras.layers import Activation, Dense, Flatten,Reshape
tfd = tfp.distributions
from keras.models import Sequential 
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.optimizers import RMSprop
from keras import models
tfb = tfp.bijectors
tfpl = tfp.layers
tfb = tfp.bijectors
import numpy as np
import matplotlib.pyplot as plt 

# multiplication and inversion bijector

In [9]:
z = tf.constant([1.,2.,3.])

In [10]:
scale = tfb.Scale(2)

In [11]:
x = scale.forward(z)

In [14]:
inversed = scale.inverse(tf.constant([5.,3.,1.]))


In [16]:
print(inversed)

tf.Tensor([2.5 1.5 0.5], shape=(3,), dtype=float32)


# scale_and_shift bijector

In [18]:
scale = tfb.Scale(2.)
shift = tfb.Shift(1.)

In [19]:
scale_and_shift = tfb.Chain([shift,scale])

In [21]:
scale_and_shift.forward(z)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3., 5., 7.], dtype=float32)>

In [22]:
scale_and_shift.inverse(tf.constant([2.,5.,8.]))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.5, 2. , 3.5], dtype=float32)>